[package]
name = "api"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "entity", "migration"]

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
sea-orm = { version = "0.12", features = [
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }
futures = "0.3.30"
dotenvy = "0.15.7"
chrono = "0.4.38"
poem-openapi = { version = "5.0.2", features = ["swagger-ui"] }
cargo-watch = "8.5.2"
serde = "1.0.203"
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-s3 = "1.42.0"
entity = { path = "entity" }
migration = { path = "migration" } # depends on your needs
poem = "3.0.0"
