openapi: 3.0.0
info:
  title: API
  version: '1.0'
servers:
- url: http://localhost:8000
tags:
- name: Event
- name: Info
- name: Review
- name: Upload
paths:
  /reviews:
    post:
      tags:
      - Review
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/InputModel'
        required: true
      responses:
        '201':
          description: Returns when the review is successfully created.
        '400':
          description: The user has sent bad data.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Issue adding the review to the database.
    get:
      tags:
      - Review
      responses:
        '201':
          description: Returns when the review is successfully created.
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '500':
          description: Likely an issue with the database connection.
  /events:
    get:
      tags:
      - Event
      responses:
        '200':
          description: Returns a list of the events
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventDto'
        '500':
          description: Likely an issue with the database connection.
    post:
      tags:
      - Event
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/EventInputModel'
        required: true
      responses:
        '200':
          description: Returns a list of the events
        '500':
          description: Likely an issue with the database connection.
  /events/attendee:
    post:
      tags:
      - Event
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/AttendeeInputModel'
        required: true
      responses:
        '200':
          description: Returns a list of the events
        '500':
          description: Likely an issue with the database connection.
  /upload/presigned-link:
    get:
      tags:
      - Upload
      responses:
        '200':
          description: Returns a list of the events
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/PresignedLinkDto'
        '500':
          description: Likely an issue with the database connection.
  /info:
    get:
      tags:
      - Info
      responses:
        '200':
          description: Returns the last deployment time
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    Attendee:
      type: object
      required:
      - id
      - event_id
      - name
      - created_at
      properties:
        id:
          type: integer
          format: int32
        event_id:
          type: integer
          format: int32
        name:
          type: string
        created_at:
          type: string
          format: naive-date-time
    AttendeeInputModel:
      type: object
      required:
      - name
      - event_id
      properties:
        name:
          type: string
        event_id:
          type: integer
          format: int32
    ErrorMessage:
      type: object
      required:
      - message
      properties:
        message:
          type: string
    EventDto:
      type: object
      required:
      - id
      - name
      - location
      - description
      - starts_at
      - ends_at
      - attendees
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        location:
          type: string
        description:
          type: string
        starts_at:
          type: string
        ends_at:
          type: string
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/Attendee'
    EventInputModel:
      type: object
      required:
      - name
      - location
      - description
      - starts_at
      - ends_at
      properties:
        name:
          type: string
        location:
          type: string
        description:
          type: string
        starts_at:
          type: string
        ends_at:
          type: string
    InputModel:
      type: object
      required:
      - name
      - title
      - description
      - stars
      properties:
        name:
          type: string
        title:
          type: string
        description:
          type: string
        stars:
          type: integer
          format: int32
    PresignedLinkDto:
      type: object
      required:
      - presigned_link
      properties:
        presigned_link:
          type: string
    Review:
      type: object
      required:
      - id
      - name
      - title
      - description
      - stars
      - is_archived
      - created_at
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        title:
          type: string
        description:
          type: string
        stars:
          type: integer
          format: int32
        is_archived:
          type: boolean
        created_at:
          type: string
          format: naive-date-time
