openapi: 3.0.0
info:
  title: API
  version: '1.0'
servers:
- url: http://localhost:8000
tags:
- name: Event
- name: Info
paths:
  /events:
    get:
      tags:
      - Event
      responses:
        '200':
          description: Returns a list of the events
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EventResponse'
        '500':
          description: Likely an issue with the database connection.
  /info:
    get:
      tags:
      - Info
      responses:
        '200':
          description: Returns the last deployment time
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    Attendee:
      type: object
      required:
      - id
      - event_id
      - name
      - created_at
      properties:
        id:
          type: integer
          format: int32
        event_id:
          type: integer
          format: int32
        name:
          type: string
        created_at:
          type: string
          format: naive-date-time
    Event:
      type: object
      required:
      - id
      - name
      - location
      - description
      - starts_at
      - ends_at
      - is_archived
      - created_at
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        location:
          type: string
        description:
          type: string
        starts_at:
          type: string
          format: naive-date-time
        ends_at:
          type: string
          format: naive-date-time
        is_archived:
          type: boolean
        created_at:
          type: string
          format: naive-date-time
    EventResponse:
      type: object
      required:
      - event
      - attendees
      properties:
        event:
          $ref: '#/components/schemas/Event'
        attendees:
          type: array
          items:
            $ref: '#/components/schemas/Attendee'
