openapi: 3.0.0
info:
  title: API
  version: '1.0'
servers:
- url: http://localhost:8000
tags:
- name: Event
- name: Info
- name: Review
paths:
  /reviews:
    post:
      tags:
      - Review
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              $ref: '#/components/schemas/InputModel'
        required: true
      responses:
        '201':
          description: Returns when the review is successfully created.
        '400':
          description: The user has sent bad data.
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '500':
          description: Issue adding the review to the database.
    get:
      tags:
      - Review
      responses:
        '201':
          description: Returns when the review is successfully created.
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
        '500':
          description: Likely an issue with the database connection.
  /event:
    get:
      tags:
      - Event
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /event/create:
    post:
      tags:
      - Event
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /event/delete:
    delete:
      tags:
      - Event
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /info:
    get:
      tags:
      - Info
      responses:
        '200':
          description: Returns when the review is successfully created.
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    ErrorMessage:
      type: object
      required:
      - message
      properties:
        message:
          type: string
    InputModel:
      type: object
      required:
      - name
      - title
      - description
      - stars
      properties:
        name:
          type: string
        title:
          type: string
        description:
          type: string
        stars:
          type: integer
          format: int32
    Review:
      type: object
      required:
      - id
      - name
      - title
      - description
      - stars
      - is_archived
      - created_at
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
        title:
          type: string
        description:
          type: string
        stars:
          type: integer
          format: int32
        is_archived:
          type: boolean
        created_at:
          type: string
          format: naive-date-time
