/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/events": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Returns a list of the events */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json; charset=utf-8": components["schemas"]["EventDTO"][]
          }
        }
        /** @description Likely an issue with the database connection. */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/info": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Returns the last deployment time */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "text/plain; charset=utf-8": string
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Attendee: {
      /** Format: int32 */
      id: number
      /** Format: int32 */
      event_id: number
      name: string
      /** Format: naive-date-time */
      created_at: string
    }
    EventDTO: {
      /** Format: int32 */
      id: number
      name: string
      location: string
      description: string
      /** Format: naive-date-time */
      starts_at: string
      /** Format: naive-date-time */
      ends_at: string
      attendees: components["schemas"]["Attendee"][]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
