name: Rust Server CI/CD

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/api

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Rust server
        run: cargo build --release

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: '/packages/api/target/release/'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '~/api/'
          SCRIPT_BEFORE: |
            sudo systemctl stop rust-api.service
          SCRIPT_AFTER: |
            sudo systemctl start rust-api.service
